### ISSUE TITLE
Missing REAME file? leads to failed installation

### ISSUE THREAD

**Issue by mbhall88** [wdecoster/nanostat#18]
When trying to install the latest version `v1.1.1` am getting the following error message

```
$ pip3 install nanostat==1.1.1
Installing nanostat==1.1.1…
Collecting nanostat==1.1.1
  Downloading https://files.pythonhosted.org/packages/21/1f/ceb88dc5985145d9291c41c31a7ea185350074370f26f23c9c2ac41cf445/NanoStat-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4h/4xhr7tqd11z91bxd30tb_sm0k0lp30/T/pip-install-ztbbxfc4/nanostat/setup.py", line 14, in <module>
        long_description=open(path.join(here, "README.md")).read(),
      File "/Users/mbhall88/.local/share/virtualenvs/tmp-v6xdJMbY/bin/../lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/4h/4xhr7tqd11z91bxd30tb_sm0k0lp30/T/pip-install-ztbbxfc4/nanostat/README.md'

    ----------------------------------------

Error:  An error occurred while installing nanostat==1.1.1!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4h/4xhr7tqd11z91bxd30tb_sm0k0lp30/T/pip-install-ztbbxfc4/nanostat/
```

**Comment by wdecoster** [comment]
Thanks for reporting this. Apparently, I forgot to add the README.md to the MANIFEST.in when I started using the .md file for creating the description on PyPI. This should be solved in NanoStat v1.1.2, which I just pushed to PyPI.

Cheers,
Wouter
