### ISSUE TITLE
Error multiple HD-lines

### ISSUE THREAD

**Issue by sarah872** [wdecoster/nanostat#21]
I am getting an error when I input `bam` files:

```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/apps/python3/3.7.0/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/apps/python3/3.7.0/lib/python3.7/concurrent/futures/process.py", line 191, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/apps/python3/3.7.0/lib/python3.7/concurrent/futures/process.py", line 191, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/user/viehboeck/00_scripts/py3-venv/lib/python3.7/site-packages/nanoget/nanoget.py", line 285, in process_bam
    samfile = check_bam(bam)
  File "/home/user/viehboeck/00_scripts/py3-venv/lib/python3.7/site-packages/nanoget/nanoget.py", line 259, in check_bam
    if not samfile.header['HD']['SO'] == 'coordinate':
  File "pysam/libcalignmentfile.pyx", line 540, in pysam.libcalignmentfile.AlignmentHeader.__getitem__
  File "pysam/libcalignmentfile.pyx", line 457, in pysam.libcalignmentfile.AlignmentHeader.to_dict
ValueError: multiple 'HD' lines are not permitted
"""

```

When I do `grep "^@HD" file.sam`, I only get one hit.

**Comment by wdecoster** [comment]
How did you obtain this bam? Can you show me the header? `samtools view -H yourfile.bam`
