### ISSUE TITLE
running the ccommand

### ISSUE THREAD

**Issue by Dymphan** [wdecoster/nanostat#28]
I have down loaded nanopack using **pip install nanopack**. After installation I have copied the NanoStat python fille from **.local/bin** to **/usr/bin**. When I run the command **NanoStat -h** I get the following error.

Traceback (most recent call last):
  File "/usr/bin/NanoStat", line 7, in <module>
    from nanostat.NanoStat import main
  File "/home/dymphan/.local/lib/python2.7/site-packages/nanostat/NanoStat.py", line 34, in <module>
    import nanoget
  File "/home/dymphan/.local/lib/python2.7/site-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/home/dymphan/.local/lib/python2.7/site-packages/nanoget/nanoget.py", line 29, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

Please help.

**Comment by Dymphan** [comment]
I installed with pip3 now its working. Also need to install cython to install nanopack.

**Comment by wdecoster** [comment]
Glad to hear you could solve the issues!

**Comment by Dymphan** [comment]
Thank you
